name: Test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/environment.yml

    - name: lint
      run: ./node_modules/.bin/standard

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/environment.yml

    - name: test
      run: ./node_modules/.bin/jest --ci
